// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jym0818/mywe/interactive/events"
	"github.com/jym0818/mywe/interactive/grpc"
	"github.com/jym0818/mywe/interactive/ioc"
	"github.com/jym0818/mywe/interactive/repository"
	"github.com/jym0818/mywe/interactive/repository/cache"
	"github.com/jym0818/mywe/interactive/repository/dao"
	"github.com/jym0818/mywe/interactive/service"
)

// Injectors from wire.go:

func InitGRPCServer() *App {
	db := ioc.InitDB()
	interactiveDao := dao.NewinteractiveDao(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewinteractiveCache(cmdable)
	interactiveRepository := repository.NewinteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service.NewinteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServer(interactiveServiceServer)
	logger := ioc.InitLogger()
	client := ioc.InitKafka()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(logger, interactiveRepository, client)
	v := ioc.NewConsumers(interactiveReadEventConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var interactive = wire.NewSet(service.NewinteractiveService, repository.NewinteractiveRepository, dao.NewinteractiveDao, cache.NewinteractiveCache)
