// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jym0818/mywe/internal/repository"
	"github.com/jym0818/mywe/internal/repository/cache"
	"github.com/jym0818/mywe/internal/repository/dao"
	"github.com/jym0818/mywe/internal/service"
	"github.com/jym0818/mywe/internal/web"
	"github.com/jym0818/mywe/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	v := ioc.InitHandler(cmdable)
	db := ioc.InitDB()
	userDAO := dao.NewuserDAO(db)
	userCache := cache.NewuserCache(cmdable)
	userRepository := repository.NewuserRepository(userDAO, userCache)
	userService := service.NewuserService(userRepository)
	smsService := ioc.InitSMS()
	codeCache := cache.NewcodeCache(cmdable)
	codeRepository := repository.NewcodeRepository(codeCache)
	codeService := service.NewCodeService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := ioc.InitWeb(v, userHandler)
	app := &App{
		server: engine,
	}
	return app
}

// wire.go:

var user = wire.NewSet(web.NewUserHandler, service.NewuserService, repository.NewuserRepository, dao.NewuserDAO, cache.NewuserCache)

var code = wire.NewSet(service.NewCodeService, repository.NewcodeRepository, cache.NewcodeCache)
